// GENERATED by `pnpm db:types` (supabase gen types --local) from supabase/migrations.
// Do not edit by hand. Regenerate after every schema change.


export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export type Database = {
  
  "public": {
          Tables: {
            "addresses": {
                  Row: {
                    "city": string,"country": string,"created_at": string,"full_name": string,"id": string,"is_default": boolean,"label": string | null,"line1": string,"line2": string | null,"phone": string | null,"state": string,"updated_at": string,"user_id": string,"zip_code": string
                  }
                  Insert: {
                    "city": string,"country"?: string,"created_at"?: string,"full_name": string,"id"?: string,"is_default"?: boolean,"label"?: string | null,"line1": string,"line2"?: string | null,"phone"?: string | null,"state": string,"updated_at"?: string,"user_id": string,"zip_code": string
                  }
                  Update: {
                    "city"?: string,"country"?: string,"created_at"?: string,"full_name"?: string,"id"?: string,"is_default"?: boolean,"label"?: string | null,"line1"?: string,"line2"?: string | null,"phone"?: string | null,"state"?: string,"updated_at"?: string,"user_id"?: string,"zip_code"?: string
                  }
                  Relationships: [
                    {
      foreignKeyName: "addresses_user_id_fkey"
      columns: ["user_id"]
isOneToOne: false
      referencedRelation: "profiles"
      referencedColumns: ["id"]
    }
                  ]
                },"admin_emails": {
                  Row: {
                    "created_at": string,"email": string,"note": string | null
                  }
                  Insert: {
                    "created_at"?: string,"email": string,"note"?: string | null
                  }
                  Update: {
                    "created_at"?: string,"email"?: string,"note"?: string | null
                  }
                  Relationships: [
                    
                  ]
                },"admin_error_events": {
                  Row: {
                    "context": NonNullable<Json>,"created_at": string,"event": string,"id": string
                  }
                  Insert: {
                    "context"?: NonNullable<Json>,"created_at"?: string,"event": string,"id"?: string
                  }
                  Update: {
                    "context"?: NonNullable<Json>,"created_at"?: string,"event"?: string,"id"?: string
                  }
                  Relationships: [
                    
                  ]
                },"app_settings": {
                  Row: {
                    "key": string,"updated_at": string,"value": NonNullable<Json>
                  }
                  Insert: {
                    "key": string,"updated_at"?: string,"value": NonNullable<Json>
                  }
                  Update: {
                    "key"?: string,"updated_at"?: string,"value"?: NonNullable<Json>
                  }
                  Relationships: [
                    
                  ]
                },"categories": {
                  Row: {
                    "created_at": string,"id": string,"is_active": boolean,"name": string,"parent_id": string | null,"product_type": Database["public"]['Enums']["product_type"],"slug": string,"sort_order": number,"updated_at": string
                  }
                  Insert: {
                    "created_at"?: string,"id"?: string,"is_active"?: boolean,"name": string,"parent_id"?: string | null,"product_type": Database["public"]['Enums']["product_type"],"slug": string,"sort_order"?: number,"updated_at"?: string
                  }
                  Update: {
                    "created_at"?: string,"id"?: string,"is_active"?: boolean,"name"?: string,"parent_id"?: string | null,"product_type"?: Database["public"]['Enums']["product_type"],"slug"?: string,"sort_order"?: number,"updated_at"?: string
                  }
                  Relationships: [
                    {
      foreignKeyName: "categories_parent_id_product_type_fkey"
      columns: ["parent_id","product_type"]
isOneToOne: false
      referencedRelation: "categories"
      referencedColumns: ["id","product_type"]
    },{
      foreignKeyName: "categories_parent_id_product_type_fkey"
      columns: ["parent_id","product_type"]
isOneToOne: false
      referencedRelation: "store_categories"
      referencedColumns: ["id","product_type"]
    }
                  ]
                },"cycles": {
                  Row: {
                    "arrived_at": string | null,"awb": string | null,"closed_at": string | null,"code": string,"created_at": string,"cutoff_at": string,"duty_cents": number | null,"est_arrival_on": string,"est_export_on": string | null,"exported_at": string | null,"forwarder": string | null,"freight_cents": number | null,"fx_inr_per_usd": number | null,"id": string,"notes": string | null,"status": Database["public"]['Enums']["cycle_status"],"updated_at": string,"_next_cycle_dates": {
              "cutoff_at": string,"est_arrival_on": string,"est_export_on": string
            } | null
                  }
                  Insert: {
                    "arrived_at"?: string | null,"awb"?: string | null,"closed_at"?: string | null,"code": string,"created_at"?: string,"cutoff_at": string,"duty_cents"?: number | null,"est_arrival_on": string,"est_export_on"?: string | null,"exported_at"?: string | null,"forwarder"?: string | null,"freight_cents"?: number | null,"fx_inr_per_usd"?: number | null,"id"?: string,"notes"?: string | null,"status"?: Database["public"]['Enums']["cycle_status"],"updated_at"?: string
                  }
                  Update: {
                    "arrived_at"?: string | null,"awb"?: string | null,"closed_at"?: string | null,"code"?: string,"created_at"?: string,"cutoff_at"?: string,"duty_cents"?: number | null,"est_arrival_on"?: string,"est_export_on"?: string | null,"exported_at"?: string | null,"forwarder"?: string | null,"freight_cents"?: number | null,"fx_inr_per_usd"?: number | null,"id"?: string,"notes"?: string | null,"status"?: Database["public"]['Enums']["cycle_status"],"updated_at"?: string
                  }
                  Relationships: [
                    
                  ]
                },"email_outbox": {
                  Row: {
                    "attempts": number,"created_at": string,"id": string,"kind": string,"last_error": string | null,"next_attempt_at": string,"payload": NonNullable<Json>,"provider_message_id": string | null,"recipient": string,"sent_at": string | null,"status": string
                  }
                  Insert: {
                    "attempts"?: number,"created_at"?: string,"id"?: string,"kind": string,"last_error"?: string | null,"next_attempt_at"?: string,"payload": NonNullable<Json>,"provider_message_id"?: string | null,"recipient": string,"sent_at"?: string | null,"status"?: string
                  }
                  Update: {
                    "attempts"?: number,"created_at"?: string,"id"?: string,"kind"?: string,"last_error"?: string | null,"next_attempt_at"?: string,"payload"?: NonNullable<Json>,"provider_message_id"?: string | null,"recipient"?: string,"sent_at"?: string | null,"status"?: string
                  }
                  Relationships: [
                    
                  ]
                },"failed_reconciliations": {
                  Row: {
                    "amount_cents": number | null,"created_at": string,"currency": string | null,"customer_email": string | null,"error_reason": string,"id": string,"metadata": Json | null,"payment_intent_id": string,"resolved_at": string | null,"resolved_by": string | null,"stripe_event_id": string | null
                  }
                  Insert: {
                    "amount_cents"?: number | null,"created_at"?: string,"currency"?: string | null,"customer_email"?: string | null,"error_reason": string,"id"?: string,"metadata"?: Json | null,"payment_intent_id": string,"resolved_at"?: string | null,"resolved_by"?: string | null,"stripe_event_id"?: string | null
                  }
                  Update: {
                    "amount_cents"?: number | null,"created_at"?: string,"currency"?: string | null,"customer_email"?: string | null,"error_reason"?: string,"id"?: string,"metadata"?: Json | null,"payment_intent_id"?: string,"resolved_at"?: string | null,"resolved_by"?: string | null,"stripe_event_id"?: string | null
                  }
                  Relationships: [
                    
                  ]
                },"newsletter_subscribers": {
                  Row: {
                    "created_at": string,"email": string,"id": string,"source": string
                  }
                  Insert: {
                    "created_at"?: string,"email": string,"id"?: string,"source"?: string
                  }
                  Update: {
                    "created_at"?: string,"email"?: string,"id"?: string,"source"?: string
                  }
                  Relationships: [
                    
                  ]
                },"order_events": {
                  Row: {
                    "actor": string | null,"created_at": string,"id": string,"internal_note": string | null,"kind": string,"message": string | null,"order_id": string,"visible_to_customer": boolean
                  }
                  Insert: {
                    "actor"?: string | null,"created_at"?: string,"id"?: string,"internal_note"?: string | null,"kind": string,"message"?: string | null,"order_id": string,"visible_to_customer"?: boolean
                  }
                  Update: {
                    "actor"?: string | null,"created_at"?: string,"id"?: string,"internal_note"?: string | null,"kind"?: string,"message"?: string | null,"order_id"?: string,"visible_to_customer"?: boolean
                  }
                  Relationships: [
                    {
      foreignKeyName: "order_events_actor_fkey"
      columns: ["actor"]
isOneToOne: false
      referencedRelation: "profiles"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "order_events_order_id_fkey"
      columns: ["order_id"]
isOneToOne: false
      referencedRelation: "orders"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "order_events_order_id_fkey"
      columns: ["order_id"]
isOneToOne: false
      referencedRelation: "store_orders"
      referencedColumns: ["id"]
    }
                  ]
                },"order_items": {
                  Row: {
                    "created_at": string,"id": string,"order_id": string,"product_id": string | null,"product_name": string,"quantity": number,"region_name": string,"status": Database["public"]['Enums']["order_item_status"],"total_price_cents": number,"unit_price_cents": number,"variant_id": string | null,"variant_label": string
                  }
                  Insert: {
                    "created_at"?: string,"id"?: string,"order_id": string,"product_id"?: string | null,"product_name": string,"quantity": number,"region_name": string,"status"?: Database["public"]['Enums']["order_item_status"],"total_price_cents": number,"unit_price_cents": number,"variant_id"?: string | null,"variant_label": string
                  }
                  Update: {
                    "created_at"?: string,"id"?: string,"order_id"?: string,"product_id"?: string | null,"product_name"?: string,"quantity"?: number,"region_name"?: string,"status"?: Database["public"]['Enums']["order_item_status"],"total_price_cents"?: number,"unit_price_cents"?: number,"variant_id"?: string | null,"variant_label"?: string
                  }
                  Relationships: [
                    {
      foreignKeyName: "order_items_order_id_fkey"
      columns: ["order_id"]
isOneToOne: false
      referencedRelation: "orders"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "order_items_order_id_fkey"
      columns: ["order_id"]
isOneToOne: false
      referencedRelation: "store_orders"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "order_items_product_id_fkey"
      columns: ["product_id"]
isOneToOne: false
      referencedRelation: "products"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "order_items_product_id_fkey"
      columns: ["product_id"]
isOneToOne: false
      referencedRelation: "store_products"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "order_items_variant_id_fkey"
      columns: ["variant_id"]
isOneToOne: false
      referencedRelation: "product_variants"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "order_items_variant_id_fkey"
      columns: ["variant_id"]
isOneToOne: false
      referencedRelation: "store_variants"
      referencedColumns: ["id"]
    }
                  ]
                },"order_moves": {
                  Row: {
                    "decided_at": string | null,"earlier": boolean,"from_cycle_id": string,"id": string,"moved_at": string,"moved_by": string | null,"note": string | null,"offer_cents": number | null,"offer_from": string | null,"offer_status": Database["public"]['Enums']["move_offer_status"],"offer_to": string | null,"order_id": string,"payment_intent_id": string | null,"shipped_confirmed_at": string | null,"to_cycle_id": string
                  }
                  Insert: {
                    "decided_at"?: string | null,"earlier": boolean,"from_cycle_id": string,"id"?: string,"moved_at"?: string,"moved_by"?: string | null,"note"?: string | null,"offer_cents"?: number | null,"offer_from"?: string | null,"offer_status"?: Database["public"]['Enums']["move_offer_status"],"offer_to"?: string | null,"order_id": string,"payment_intent_id"?: string | null,"shipped_confirmed_at"?: string | null,"to_cycle_id": string
                  }
                  Update: {
                    "decided_at"?: string | null,"earlier"?: boolean,"from_cycle_id"?: string,"id"?: string,"moved_at"?: string,"moved_by"?: string | null,"note"?: string | null,"offer_cents"?: number | null,"offer_from"?: string | null,"offer_status"?: Database["public"]['Enums']["move_offer_status"],"offer_to"?: string | null,"order_id"?: string,"payment_intent_id"?: string | null,"shipped_confirmed_at"?: string | null,"to_cycle_id"?: string
                  }
                  Relationships: [
                    {
      foreignKeyName: "order_moves_from_cycle_id_fkey"
      columns: ["from_cycle_id"]
isOneToOne: false
      referencedRelation: "cycles"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "order_moves_moved_by_fkey"
      columns: ["moved_by"]
isOneToOne: false
      referencedRelation: "profiles"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "order_moves_order_id_fkey"
      columns: ["order_id"]
isOneToOne: false
      referencedRelation: "orders"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "order_moves_order_id_fkey"
      columns: ["order_id"]
isOneToOne: false
      referencedRelation: "store_orders"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "order_moves_to_cycle_id_fkey"
      columns: ["to_cycle_id"]
isOneToOne: false
      referencedRelation: "cycles"
      referencedColumns: ["id"]
    }
                  ]
                },"orders": {
                  Row: {
                    "carrier": string | null,"created_at": string,"currency": string,"cycle_id": string | null,"discount_cents": number,"email": string,"est_delivery_from": string | null,"est_delivery_to": string | null,"fulfilment_mode": Database["public"]['Enums']["fulfilment_mode"],"id": string,"notes": string | null,"order_number": string,"payment_intent_id": string | null,"payment_status": Database["public"]['Enums']["payment_status"],"promo_code_id": string | null,"refunded_cents": number,"shipping_address": NonNullable<Json>,"shipping_cents": number,"shipping_method": Database["public"]['Enums']["shipping_method"],"status": Database["public"]['Enums']["order_status"],"subtotal_cents": number,"tax_cents": number,"total_cents": number,"tracking_number": string | null,"updated_at": string,"user_id": string | null
                  }
                  Insert: {
                    "carrier"?: string | null,"created_at"?: string,"currency"?: string,"cycle_id"?: string | null,"discount_cents"?: number,"email": string,"est_delivery_from"?: string | null,"est_delivery_to"?: string | null,"fulfilment_mode"?: Database["public"]['Enums']["fulfilment_mode"],"id"?: string,"notes"?: string | null,"order_number"?: string,"payment_intent_id"?: string | null,"payment_status"?: Database["public"]['Enums']["payment_status"],"promo_code_id"?: string | null,"refunded_cents"?: number,"shipping_address": NonNullable<Json>,"shipping_cents"?: number,"shipping_method"?: Database["public"]['Enums']["shipping_method"],"status"?: Database["public"]['Enums']["order_status"],"subtotal_cents": number,"tax_cents"?: number,"total_cents": number,"tracking_number"?: string | null,"updated_at"?: string,"user_id"?: string | null
                  }
                  Update: {
                    "carrier"?: string | null,"created_at"?: string,"currency"?: string,"cycle_id"?: string | null,"discount_cents"?: number,"email"?: string,"est_delivery_from"?: string | null,"est_delivery_to"?: string | null,"fulfilment_mode"?: Database["public"]['Enums']["fulfilment_mode"],"id"?: string,"notes"?: string | null,"order_number"?: string,"payment_intent_id"?: string | null,"payment_status"?: Database["public"]['Enums']["payment_status"],"promo_code_id"?: string | null,"refunded_cents"?: number,"shipping_address"?: NonNullable<Json>,"shipping_cents"?: number,"shipping_method"?: Database["public"]['Enums']["shipping_method"],"status"?: Database["public"]['Enums']["order_status"],"subtotal_cents"?: number,"tax_cents"?: number,"total_cents"?: number,"tracking_number"?: string | null,"updated_at"?: string,"user_id"?: string | null
                  }
                  Relationships: [
                    {
      foreignKeyName: "orders_cycle_id_fkey"
      columns: ["cycle_id"]
isOneToOne: false
      referencedRelation: "cycles"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "orders_promo_code_id_fkey"
      columns: ["promo_code_id"]
isOneToOne: false
      referencedRelation: "promo_codes"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "orders_user_id_fkey"
      columns: ["user_id"]
isOneToOne: false
      referencedRelation: "profiles"
      referencedColumns: ["id"]
    }
                  ]
                },"pending_orders": {
                  Row: {
                    "checkout_payload": NonNullable<Json>,"created_at": string,"id": string,"payment_intent_id": string,"reconciled_at": string | null,"reconciled_by": string | null
                  }
                  Insert: {
                    "checkout_payload": NonNullable<Json>,"created_at"?: string,"id"?: string,"payment_intent_id": string,"reconciled_at"?: string | null,"reconciled_by"?: string | null
                  }
                  Update: {
                    "checkout_payload"?: NonNullable<Json>,"created_at"?: string,"id"?: string,"payment_intent_id"?: string,"reconciled_at"?: string | null,"reconciled_by"?: string | null
                  }
                  Relationships: [
                    
                  ]
                },"pickups": {
                  Row: {
                    "created_at": string,"cycle_id": string,"id": string,"note": string | null,"order_item_id": string,"payout_id": string | null,"photo_path": string | null,"picked_at": string | null,"picked_by": string | null,"quantity": number,"shop_price_paise": number | null,"status": Database["public"]['Enums']["pickup_status"],"updated_at": string,"variant_id": string,"vendor_id": string
                  }
                  Insert: {
                    "created_at"?: string,"cycle_id": string,"id"?: string,"note"?: string | null,"order_item_id": string,"payout_id"?: string | null,"photo_path"?: string | null,"picked_at"?: string | null,"picked_by"?: string | null,"quantity": number,"shop_price_paise"?: number | null,"status"?: Database["public"]['Enums']["pickup_status"],"updated_at"?: string,"variant_id": string,"vendor_id": string
                  }
                  Update: {
                    "created_at"?: string,"cycle_id"?: string,"id"?: string,"note"?: string | null,"order_item_id"?: string,"payout_id"?: string | null,"photo_path"?: string | null,"picked_at"?: string | null,"picked_by"?: string | null,"quantity"?: number,"shop_price_paise"?: number | null,"status"?: Database["public"]['Enums']["pickup_status"],"updated_at"?: string,"variant_id"?: string,"vendor_id"?: string
                  }
                  Relationships: [
                    {
      foreignKeyName: "pickups_cycle_id_fkey"
      columns: ["cycle_id"]
isOneToOne: false
      referencedRelation: "cycles"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "pickups_order_item_id_fkey"
      columns: ["order_item_id"]
isOneToOne: true
      referencedRelation: "order_items"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "pickups_order_item_id_fkey"
      columns: ["order_item_id"]
isOneToOne: true
      referencedRelation: "store_order_items"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "pickups_payout_id_fkey"
      columns: ["payout_id"]
isOneToOne: false
      referencedRelation: "vendor_payouts"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "pickups_picked_by_fkey"
      columns: ["picked_by"]
isOneToOne: false
      referencedRelation: "profiles"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "pickups_variant_id_fkey"
      columns: ["variant_id"]
isOneToOne: false
      referencedRelation: "product_variants"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "pickups_variant_id_fkey"
      columns: ["variant_id"]
isOneToOne: false
      referencedRelation: "store_variants"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "pickups_vendor_id_fkey"
      columns: ["vendor_id"]
isOneToOne: false
      referencedRelation: "vendors"
      referencedColumns: ["id"]
    }
                  ]
                },"pricing_settings": {
                  Row: {
                    "cycle_days": number | null,"domestic_days_max": number | null,"domestic_days_min": number | null,"duty_pct": number | null,"express_days_max": number | null,"express_days_min": number | null,"express_shipping_cents": number | null,"fast_offer_cents": number | null,"free_shipping_min_cents": number | null,"freight_cents_per_kg": number | null,"fx_inr_per_usd": number | null,"id": number,"leaving_soon_max": number,"margin_pct": number | null,"shipping_flat_cents": number | null,"stale_listing_days": number | null,"updated_at": string,"updated_by": string | null
                  }
                  Insert: {
                    "cycle_days"?: number | null,"domestic_days_max"?: number | null,"domestic_days_min"?: number | null,"duty_pct"?: number | null,"express_days_max"?: number | null,"express_days_min"?: number | null,"express_shipping_cents"?: number | null,"fast_offer_cents"?: number | null,"free_shipping_min_cents"?: number | null,"freight_cents_per_kg"?: number | null,"fx_inr_per_usd"?: number | null,"id"?: number,"leaving_soon_max"?: number,"margin_pct"?: number | null,"shipping_flat_cents"?: number | null,"stale_listing_days"?: number | null,"updated_at"?: string,"updated_by"?: string | null
                  }
                  Update: {
                    "cycle_days"?: number | null,"domestic_days_max"?: number | null,"domestic_days_min"?: number | null,"duty_pct"?: number | null,"express_days_max"?: number | null,"express_days_min"?: number | null,"express_shipping_cents"?: number | null,"fast_offer_cents"?: number | null,"free_shipping_min_cents"?: number | null,"freight_cents_per_kg"?: number | null,"fx_inr_per_usd"?: number | null,"id"?: number,"leaving_soon_max"?: number,"margin_pct"?: number | null,"shipping_flat_cents"?: number | null,"stale_listing_days"?: number | null,"updated_at"?: string,"updated_by"?: string | null
                  }
                  Relationships: [
                    {
      foreignKeyName: "pricing_settings_updated_by_fkey"
      columns: ["updated_by"]
isOneToOne: false
      referencedRelation: "profiles"
      referencedColumns: ["id"]
    }
                  ]
                },"product_media": {
                  Row: {
                    "alt_text": string,"created_at": string,"id": string,"is_primary": boolean,"product_id": string,"sort_order": number,"storage_path": string,"variant_id": string | null
                  }
                  Insert: {
                    "alt_text"?: string,"created_at"?: string,"id"?: string,"is_primary"?: boolean,"product_id": string,"sort_order"?: number,"storage_path": string,"variant_id"?: string | null
                  }
                  Update: {
                    "alt_text"?: string,"created_at"?: string,"id"?: string,"is_primary"?: boolean,"product_id"?: string,"sort_order"?: number,"storage_path"?: string,"variant_id"?: string | null
                  }
                  Relationships: [
                    {
      foreignKeyName: "product_media_product_id_fkey"
      columns: ["product_id"]
isOneToOne: false
      referencedRelation: "products"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "product_media_product_id_fkey"
      columns: ["product_id"]
isOneToOne: false
      referencedRelation: "store_products"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "product_media_variant_id_fkey"
      columns: ["variant_id"]
isOneToOne: false
      referencedRelation: "product_variants"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "product_media_variant_id_fkey"
      columns: ["variant_id"]
isOneToOne: false
      referencedRelation: "store_variants"
      referencedColumns: ["id"]
    }
                  ]
                },"product_variants": {
                  Row: {
                    "created_at": string,"id": string,"is_active": boolean,"label": string,"options": NonNullable<Json>,"price_cents": number | null,"product_id": string,"qty_confirmed_at": string | null,"qty_listed": number,"qty_reserved": number,"sku": string,"sort_order": number,"updated_at": string,"weight_g": number | null
                  }
                  Insert: {
                    "created_at"?: string,"id"?: string,"is_active"?: boolean,"label": string,"options"?: NonNullable<Json>,"price_cents"?: number | null,"product_id": string,"qty_confirmed_at"?: string | null,"qty_listed"?: number,"qty_reserved"?: number,"sku": string,"sort_order"?: number,"updated_at"?: string,"weight_g"?: number | null
                  }
                  Update: {
                    "created_at"?: string,"id"?: string,"is_active"?: boolean,"label"?: string,"options"?: NonNullable<Json>,"price_cents"?: number | null,"product_id"?: string,"qty_confirmed_at"?: string | null,"qty_listed"?: number,"qty_reserved"?: number,"sku"?: string,"sort_order"?: number,"updated_at"?: string,"weight_g"?: number | null
                  }
                  Relationships: [
                    {
      foreignKeyName: "product_variants_product_id_fkey"
      columns: ["product_id"]
isOneToOne: false
      referencedRelation: "products"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "product_variants_product_id_fkey"
      columns: ["product_id"]
isOneToOne: false
      referencedRelation: "store_products"
      referencedColumns: ["id"]
    }
                  ]
                },"products": {
                  Row: {
                    "attributes": NonNullable<Json>,"category_id": string,"craft": string | null,"created_at": string,"created_by": string | null,"description": string | null,"has_origin_label": boolean,"id": string,"is_curated": boolean,"is_placeholder": boolean,"name": string,"origin_town": string | null,"price_cents": number,"product_type": Database["public"]['Enums']["product_type"],"published_at": string | null,"region_id": string,"search": unknown,"shop_price_paise": number | null,"slug": string,"status": Database["public"]['Enums']["product_status"],"story": string | null,"summary": string | null,"updated_at": string,"vendor_id": string
                  }
                  Insert: {
                    "attributes"?: NonNullable<Json>,"category_id": string,"craft"?: string | null,"created_at"?: string,"created_by"?: string | null,"description"?: string | null,"has_origin_label"?: boolean,"id"?: string,"is_curated"?: boolean,"is_placeholder"?: boolean,"name": string,"origin_town"?: string | null,"price_cents": number,"product_type": Database["public"]['Enums']["product_type"],"published_at"?: string | null,"region_id": string,"search"?: never,"shop_price_paise"?: number | null,"slug": string,"status"?: Database["public"]['Enums']["product_status"],"story"?: string | null,"summary"?: string | null,"updated_at"?: string,"vendor_id": string
                  }
                  Update: {
                    "attributes"?: NonNullable<Json>,"category_id"?: string,"craft"?: string | null,"created_at"?: string,"created_by"?: string | null,"description"?: string | null,"has_origin_label"?: boolean,"id"?: string,"is_curated"?: boolean,"is_placeholder"?: boolean,"name"?: string,"origin_town"?: string | null,"price_cents"?: number,"product_type"?: Database["public"]['Enums']["product_type"],"published_at"?: string | null,"region_id"?: string,"search"?: never,"shop_price_paise"?: number | null,"slug"?: string,"status"?: Database["public"]['Enums']["product_status"],"story"?: string | null,"summary"?: string | null,"updated_at"?: string,"vendor_id"?: string
                  }
                  Relationships: [
                    {
      foreignKeyName: "products_category_id_product_type_fkey"
      columns: ["category_id","product_type"]
isOneToOne: false
      referencedRelation: "categories"
      referencedColumns: ["id","product_type"]
    },{
      foreignKeyName: "products_category_id_product_type_fkey"
      columns: ["category_id","product_type"]
isOneToOne: false
      referencedRelation: "store_categories"
      referencedColumns: ["id","product_type"]
    },{
      foreignKeyName: "products_created_by_fkey"
      columns: ["created_by"]
isOneToOne: false
      referencedRelation: "profiles"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "products_region_id_fkey"
      columns: ["region_id"]
isOneToOne: false
      referencedRelation: "regions"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "products_region_id_fkey"
      columns: ["region_id"]
isOneToOne: false
      referencedRelation: "store_regions"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "products_vendor_id_fkey"
      columns: ["vendor_id"]
isOneToOne: false
      referencedRelation: "vendors"
      referencedColumns: ["id"]
    }
                  ]
                },"profiles": {
                  Row: {
                    "created_at": string,"desk": Database["public"]['Enums']["ops_desk"] | null,"email": string | null,"full_name": string | null,"id": string,"phone": string | null,"role": Database["public"]['Enums']["app_role"],"updated_at": string
                  }
                  Insert: {
                    "created_at"?: string,"desk"?: Database["public"]['Enums']["ops_desk"] | null,"email"?: string | null,"full_name"?: string | null,"id": string,"phone"?: string | null,"role"?: Database["public"]['Enums']["app_role"],"updated_at"?: string
                  }
                  Update: {
                    "created_at"?: string,"desk"?: Database["public"]['Enums']["ops_desk"] | null,"email"?: string | null,"full_name"?: string | null,"id"?: string,"phone"?: string | null,"role"?: Database["public"]['Enums']["app_role"],"updated_at"?: string
                  }
                  Relationships: [
                    
                  ]
                },"promo_codes": {
                  Row: {
                    "code": string,"created_at": string,"discount_type": Database["public"]['Enums']["discount_type"],"discount_value": number,"id": string,"is_active": boolean,"max_uses": number | null,"min_order_cents": number,"updated_at": string,"uses_count": number,"valid_from": string | null,"valid_until": string | null
                  }
                  Insert: {
                    "code": string,"created_at"?: string,"discount_type": Database["public"]['Enums']["discount_type"],"discount_value": number,"id"?: string,"is_active"?: boolean,"max_uses"?: number | null,"min_order_cents"?: number,"updated_at"?: string,"uses_count"?: number,"valid_from"?: string | null,"valid_until"?: string | null
                  }
                  Update: {
                    "code"?: string,"created_at"?: string,"discount_type"?: Database["public"]['Enums']["discount_type"],"discount_value"?: number,"id"?: string,"is_active"?: boolean,"max_uses"?: number | null,"min_order_cents"?: number,"updated_at"?: string,"uses_count"?: number,"valid_from"?: string | null,"valid_until"?: string | null
                  }
                  Relationships: [
                    
                  ]
                },"region_photos": {
                  Row: {
                    "alt_text": string,"created_at": string,"id": string,"region_id": string,"sort_order": number,"storage_path": string
                  }
                  Insert: {
                    "alt_text": string,"created_at"?: string,"id"?: string,"region_id": string,"sort_order"?: number,"storage_path": string
                  }
                  Update: {
                    "alt_text"?: string,"created_at"?: string,"id"?: string,"region_id"?: string,"sort_order"?: number,"storage_path"?: string
                  }
                  Relationships: [
                    {
      foreignKeyName: "region_photos_region_id_fkey"
      columns: ["region_id"]
isOneToOne: false
      referencedRelation: "regions"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "region_photos_region_id_fkey"
      columns: ["region_id"]
isOneToOne: false
      referencedRelation: "store_regions"
      referencedColumns: ["id"]
    }
                  ]
                },"regions": {
                  Row: {
                    "accent_color": string | null,"content_status": Database["public"]['Enums']["content_status"],"created_at": string,"greeting_latin": string | null,"greeting_meaning": string | null,"greeting_native": string | null,"greeting_script": string | null,"hero_image_path": string | null,"id": string,"is_live": boolean,"languages": (string)[],"name": string,"slug": string,"sort_order": number,"story": string | null,"tagline": string | null,"updated_at": string
                  }
                  Insert: {
                    "accent_color"?: string | null,"content_status"?: Database["public"]['Enums']["content_status"],"created_at"?: string,"greeting_latin"?: string | null,"greeting_meaning"?: string | null,"greeting_native"?: string | null,"greeting_script"?: string | null,"hero_image_path"?: string | null,"id"?: string,"is_live"?: boolean,"languages"?: (string)[],"name": string,"slug": string,"sort_order"?: number,"story"?: string | null,"tagline"?: string | null,"updated_at"?: string
                  }
                  Update: {
                    "accent_color"?: string | null,"content_status"?: Database["public"]['Enums']["content_status"],"created_at"?: string,"greeting_latin"?: string | null,"greeting_meaning"?: string | null,"greeting_native"?: string | null,"greeting_script"?: string | null,"hero_image_path"?: string | null,"id"?: string,"is_live"?: boolean,"languages"?: (string)[],"name"?: string,"slug"?: string,"sort_order"?: number,"story"?: string | null,"tagline"?: string | null,"updated_at"?: string
                  }
                  Relationships: [
                    
                  ]
                },"review_photos": {
                  Row: {
                    "created_at": string,"id": string,"review_id": string,"sort_order": number,"storage_path": string
                  }
                  Insert: {
                    "created_at"?: string,"id"?: string,"review_id": string,"sort_order"?: number,"storage_path": string
                  }
                  Update: {
                    "created_at"?: string,"id"?: string,"review_id"?: string,"sort_order"?: number,"storage_path"?: string
                  }
                  Relationships: [
                    {
      foreignKeyName: "review_photos_review_id_fkey"
      columns: ["review_id"]
isOneToOne: false
      referencedRelation: "reviews"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "review_photos_review_id_fkey"
      columns: ["review_id"]
isOneToOne: false
      referencedRelation: "store_reviews"
      referencedColumns: ["id"]
    }
                  ]
                },"reviews": {
                  Row: {
                    "body": string,"created_at": string,"display_name": string,"id": string,"is_verified_buyer": boolean,"moderated_at": string | null,"moderated_by": string | null,"product_id": string,"rating": number,"status": Database["public"]['Enums']["review_status"],"updated_at": string,"user_id": string
                  }
                  Insert: {
                    "body": string,"created_at"?: string,"display_name": string,"id"?: string,"is_verified_buyer"?: boolean,"moderated_at"?: string | null,"moderated_by"?: string | null,"product_id": string,"rating": number,"status"?: Database["public"]['Enums']["review_status"],"updated_at"?: string,"user_id": string
                  }
                  Update: {
                    "body"?: string,"created_at"?: string,"display_name"?: string,"id"?: string,"is_verified_buyer"?: boolean,"moderated_at"?: string | null,"moderated_by"?: string | null,"product_id"?: string,"rating"?: number,"status"?: Database["public"]['Enums']["review_status"],"updated_at"?: string,"user_id"?: string
                  }
                  Relationships: [
                    {
      foreignKeyName: "reviews_moderated_by_fkey"
      columns: ["moderated_by"]
isOneToOne: false
      referencedRelation: "profiles"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "reviews_product_id_fkey"
      columns: ["product_id"]
isOneToOne: false
      referencedRelation: "products"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "reviews_product_id_fkey"
      columns: ["product_id"]
isOneToOne: false
      referencedRelation: "store_products"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "reviews_user_id_fkey"
      columns: ["user_id"]
isOneToOne: false
      referencedRelation: "profiles"
      referencedColumns: ["id"]
    }
                  ]
                },"stock_movements": {
                  Row: {
                    "actor": string | null,"created_at": string,"delta_listed": number,"delta_reserved": number,"id": number,"note": string | null,"reason": Database["public"]['Enums']["stock_reason"],"ref_id": string | null,"ref_type": string | null,"variant_id": string
                  }
                  Insert: {
                    "actor"?: string | null,"created_at"?: string,"delta_listed"?: number,"delta_reserved"?: number,"id"?: never,"note"?: string | null,"reason": Database["public"]['Enums']["stock_reason"],"ref_id"?: string | null,"ref_type"?: string | null,"variant_id": string
                  }
                  Update: {
                    "actor"?: string | null,"created_at"?: string,"delta_listed"?: number,"delta_reserved"?: number,"id"?: never,"note"?: string | null,"reason"?: Database["public"]['Enums']["stock_reason"],"ref_id"?: string | null,"ref_type"?: string | null,"variant_id"?: string
                  }
                  Relationships: [
                    {
      foreignKeyName: "stock_movements_variant_id_fkey"
      columns: ["variant_id"]
isOneToOne: false
      referencedRelation: "product_variants"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "stock_movements_variant_id_fkey"
      columns: ["variant_id"]
isOneToOne: false
      referencedRelation: "store_variants"
      referencedColumns: ["id"]
    }
                  ]
                },"variant_availability": {
                  Row: {
                    "available": number,"product_id": string,"updated_at": string,"variant_id": string
                  }
                  Insert: {
                    "available": number,"product_id": string,"updated_at"?: string,"variant_id": string
                  }
                  Update: {
                    "available"?: number,"product_id"?: string,"updated_at"?: string,"variant_id"?: string
                  }
                  Relationships: [
                    {
      foreignKeyName: "variant_availability_product_id_fkey"
      columns: ["product_id"]
isOneToOne: false
      referencedRelation: "products"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "variant_availability_product_id_fkey"
      columns: ["product_id"]
isOneToOne: false
      referencedRelation: "store_products"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "variant_availability_variant_id_fkey"
      columns: ["variant_id"]
isOneToOne: true
      referencedRelation: "product_variants"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "variant_availability_variant_id_fkey"
      columns: ["variant_id"]
isOneToOne: true
      referencedRelation: "store_variants"
      referencedColumns: ["id"]
    }
                  ]
                },"vendor_payouts": {
                  Row: {
                    "amount_paise": number,"created_at": string,"cycle_id": string | null,"id": string,"method": string,"note": string | null,"paid_at": string,"paid_by": string | null,"receipt_path": string | null,"reference": string | null,"vendor_id": string
                  }
                  Insert: {
                    "amount_paise": number,"created_at"?: string,"cycle_id"?: string | null,"id"?: string,"method": string,"note"?: string | null,"paid_at"?: string,"paid_by"?: string | null,"receipt_path"?: string | null,"reference"?: string | null,"vendor_id": string
                  }
                  Update: {
                    "amount_paise"?: number,"created_at"?: string,"cycle_id"?: string | null,"id"?: string,"method"?: string,"note"?: string | null,"paid_at"?: string,"paid_by"?: string | null,"receipt_path"?: string | null,"reference"?: string | null,"vendor_id"?: string
                  }
                  Relationships: [
                    {
      foreignKeyName: "vendor_payouts_cycle_id_fkey"
      columns: ["cycle_id"]
isOneToOne: false
      referencedRelation: "cycles"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "vendor_payouts_paid_by_fkey"
      columns: ["paid_by"]
isOneToOne: false
      referencedRelation: "profiles"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "vendor_payouts_vendor_id_fkey"
      columns: ["vendor_id"]
isOneToOne: false
      referencedRelation: "vendors"
      referencedColumns: ["id"]
    }
                  ]
                },"vendors": {
                  Row: {
                    "address": string | null,"created_at": string,"email": string | null,"id": string,"is_placeholder": boolean,"licences": NonNullable<Json>,"notes": string | null,"onboarded_at": string | null,"onboarded_by": string | null,"owner_name": string | null,"payment_method": string | null,"payment_reference": string | null,"phone": string | null,"photo_path": string | null,"region_id": string,"shop_name": string,"status": Database["public"]['Enums']["vendor_status"],"town": string | null,"updated_at": string,"whatsapp": string | null
                  }
                  Insert: {
                    "address"?: string | null,"created_at"?: string,"email"?: string | null,"id"?: string,"is_placeholder"?: boolean,"licences"?: NonNullable<Json>,"notes"?: string | null,"onboarded_at"?: string | null,"onboarded_by"?: string | null,"owner_name"?: string | null,"payment_method"?: string | null,"payment_reference"?: string | null,"phone"?: string | null,"photo_path"?: string | null,"region_id": string,"shop_name": string,"status"?: Database["public"]['Enums']["vendor_status"],"town"?: string | null,"updated_at"?: string,"whatsapp"?: string | null
                  }
                  Update: {
                    "address"?: string | null,"created_at"?: string,"email"?: string | null,"id"?: string,"is_placeholder"?: boolean,"licences"?: NonNullable<Json>,"notes"?: string | null,"onboarded_at"?: string | null,"onboarded_by"?: string | null,"owner_name"?: string | null,"payment_method"?: string | null,"payment_reference"?: string | null,"phone"?: string | null,"photo_path"?: string | null,"region_id"?: string,"shop_name"?: string,"status"?: Database["public"]['Enums']["vendor_status"],"town"?: string | null,"updated_at"?: string,"whatsapp"?: string | null
                  }
                  Relationships: [
                    {
      foreignKeyName: "vendors_onboarded_by_fkey"
      columns: ["onboarded_by"]
isOneToOne: false
      referencedRelation: "profiles"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "vendors_region_id_fkey"
      columns: ["region_id"]
isOneToOne: false
      referencedRelation: "regions"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "vendors_region_id_fkey"
      columns: ["region_id"]
isOneToOne: false
      referencedRelation: "store_regions"
      referencedColumns: ["id"]
    }
                  ]
                },"webhook_events": {
                  Row: {
                    "event_id": string,"event_type": string,"id": string,"processed_at": string
                  }
                  Insert: {
                    "event_id": string,"event_type": string,"id"?: string,"processed_at"?: string
                  }
                  Update: {
                    "event_id"?: string,"event_type"?: string,"id"?: string,"processed_at"?: string
                  }
                  Relationships: [
                    
                  ]
                },"wishlists": {
                  Row: {
                    "created_at": string,"product_id": string,"user_id": string
                  }
                  Insert: {
                    "created_at"?: string,"product_id": string,"user_id": string
                  }
                  Update: {
                    "created_at"?: string,"product_id"?: string,"user_id"?: string
                  }
                  Relationships: [
                    {
      foreignKeyName: "wishlists_product_id_fkey"
      columns: ["product_id"]
isOneToOne: false
      referencedRelation: "products"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "wishlists_product_id_fkey"
      columns: ["product_id"]
isOneToOne: false
      referencedRelation: "store_products"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "wishlists_user_id_fkey"
      columns: ["user_id"]
isOneToOne: false
      referencedRelation: "profiles"
      referencedColumns: ["id"]
    }
                  ]
                }
          }
          Views: {
            "store_categories": {
                  Row: {
                    "id": string | null,"name": string | null,"parent_id": string | null,"product_type": Database["public"]['Enums']["product_type"] | null,"slug": string | null,"sort_order": number | null
                  }
                  Insert: {
                           "id"?: string | null,"name"?: string | null,"parent_id"?: string | null,"product_type"?: Database["public"]['Enums']["product_type"] | null,"slug"?: string | null,"sort_order"?: number | null
                         }
                        Update: {
                           "id"?: string | null,"name"?: string | null,"parent_id"?: string | null,"product_type"?: Database["public"]['Enums']["product_type"] | null,"slug"?: string | null,"sort_order"?: number | null
                         }
                        Relationships: [
                    {
      foreignKeyName: "categories_parent_id_product_type_fkey"
      columns: ["parent_id","product_type"]
isOneToOne: false
      referencedRelation: "categories"
      referencedColumns: ["id","product_type"]
    },{
      foreignKeyName: "categories_parent_id_product_type_fkey"
      columns: ["parent_id","product_type"]
isOneToOne: false
      referencedRelation: "store_categories"
      referencedColumns: ["id","product_type"]
    }
                  ]
                },"store_media": {
                  Row: {
                    "alt_text": string | null,"id": string | null,"is_primary": boolean | null,"product_id": string | null,"sort_order": number | null,"storage_path": string | null,"variant_id": string | null
                  }
                  Relationships: [
                    {
      foreignKeyName: "product_media_product_id_fkey"
      columns: ["product_id"]
isOneToOne: false
      referencedRelation: "products"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "product_media_product_id_fkey"
      columns: ["product_id"]
isOneToOne: false
      referencedRelation: "store_products"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "product_media_variant_id_fkey"
      columns: ["variant_id"]
isOneToOne: false
      referencedRelation: "product_variants"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "product_media_variant_id_fkey"
      columns: ["variant_id"]
isOneToOne: false
      referencedRelation: "store_variants"
      referencedColumns: ["id"]
    }
                  ]
                },"store_order_events": {
                  Row: {
                    "created_at": string | null,"id": string | null,"kind": string | null,"message": string | null,"order_id": string | null
                  }
                  Relationships: [
                    {
      foreignKeyName: "order_events_order_id_fkey"
      columns: ["order_id"]
isOneToOne: false
      referencedRelation: "orders"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "order_events_order_id_fkey"
      columns: ["order_id"]
isOneToOne: false
      referencedRelation: "store_orders"
      referencedColumns: ["id"]
    }
                  ]
                },"store_order_items": {
                  Row: {
                    "id": string | null,"order_id": string | null,"product_id": string | null,"product_name": string | null,"quantity": number | null,"region_name": string | null,"status": Database["public"]['Enums']["order_item_status"] | null,"total_price_cents": number | null,"unit_price_cents": number | null,"variant_label": string | null
                  }
                  Relationships: [
                    {
      foreignKeyName: "order_items_order_id_fkey"
      columns: ["order_id"]
isOneToOne: false
      referencedRelation: "orders"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "order_items_order_id_fkey"
      columns: ["order_id"]
isOneToOne: false
      referencedRelation: "store_orders"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "order_items_product_id_fkey"
      columns: ["product_id"]
isOneToOne: false
      referencedRelation: "products"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "order_items_product_id_fkey"
      columns: ["product_id"]
isOneToOne: false
      referencedRelation: "store_products"
      referencedColumns: ["id"]
    }
                  ]
                },"store_orders": {
                  Row: {
                    "carrier": string | null,"created_at": string | null,"currency": string | null,"customer_status": string | null,"discount_cents": number | null,"email": string | null,"est_delivery_from": string | null,"est_delivery_to": string | null,"id": string | null,"order_number": string | null,"payment_status": Database["public"]['Enums']["payment_status"] | null,"refunded_cents": number | null,"shipping_address": Json | null,"shipping_cents": number | null,"shipping_method": Database["public"]['Enums']["shipping_method"] | null,"subtotal_cents": number | null,"tax_cents": number | null,"total_cents": number | null,"tracking_number": string | null
                  }
                  Insert: {
                           "carrier"?: string | null,"created_at"?: string | null,"currency"?: string | null,"customer_status"?: never,"discount_cents"?: number | null,"email"?: string | null,"est_delivery_from"?: string | null,"est_delivery_to"?: string | null,"id"?: string | null,"order_number"?: string | null,"payment_status"?: Database["public"]['Enums']["payment_status"] | null,"refunded_cents"?: number | null,"shipping_address"?: Json | null,"shipping_cents"?: number | null,"shipping_method"?: Database["public"]['Enums']["shipping_method"] | null,"subtotal_cents"?: number | null,"tax_cents"?: number | null,"total_cents"?: number | null,"tracking_number"?: string | null
                         }
                        Update: {
                           "carrier"?: string | null,"created_at"?: string | null,"currency"?: string | null,"customer_status"?: never,"discount_cents"?: number | null,"email"?: string | null,"est_delivery_from"?: string | null,"est_delivery_to"?: string | null,"id"?: string | null,"order_number"?: string | null,"payment_status"?: Database["public"]['Enums']["payment_status"] | null,"refunded_cents"?: number | null,"shipping_address"?: Json | null,"shipping_cents"?: number | null,"shipping_method"?: Database["public"]['Enums']["shipping_method"] | null,"subtotal_cents"?: number | null,"tax_cents"?: number | null,"total_cents"?: number | null,"tracking_number"?: string | null
                         }
                        Relationships: [
                    
                  ]
                },"store_products": {
                  Row: {
                    "attributes": Json | null,"category_id": string | null,"category_name": string | null,"category_slug": string | null,"craft": string | null,"description": string | null,"id": string | null,"is_curated": boolean | null,"name": string | null,"price_cents": number | null,"primary_image_path": string | null,"product_type": Database["public"]['Enums']["product_type"] | null,"published_at": string | null,"region_id": string | null,"region_name": string | null,"region_slug": string | null,"search": unknown,"slug": string | null,"story": string | null,"summary": string | null
                  }
                  Relationships: [
                    {
      foreignKeyName: "products_category_id_product_type_fkey"
      columns: ["category_id","product_type"]
isOneToOne: false
      referencedRelation: "categories"
      referencedColumns: ["id","product_type"]
    },{
      foreignKeyName: "products_category_id_product_type_fkey"
      columns: ["category_id","product_type"]
isOneToOne: false
      referencedRelation: "store_categories"
      referencedColumns: ["id","product_type"]
    },{
      foreignKeyName: "products_region_id_fkey"
      columns: ["region_id"]
isOneToOne: false
      referencedRelation: "regions"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "products_region_id_fkey"
      columns: ["region_id"]
isOneToOne: false
      referencedRelation: "store_regions"
      referencedColumns: ["id"]
    }
                  ]
                },"store_regions": {
                  Row: {
                    "accent_color": string | null,"greeting_latin": string | null,"greeting_meaning": string | null,"greeting_native": string | null,"greeting_script": string | null,"hero_image_path": string | null,"id": string | null,"is_live": boolean | null,"name": string | null,"slug": string | null,"sort_order": number | null,"story": string | null,"tagline": string | null
                  }
                  Insert: {
                           "accent_color"?: string | null,"greeting_latin"?: never,"greeting_meaning"?: never,"greeting_native"?: never,"greeting_script"?: never,"hero_image_path"?: string | null,"id"?: string | null,"is_live"?: boolean | null,"name"?: string | null,"slug"?: string | null,"sort_order"?: number | null,"story"?: never,"tagline"?: never
                         }
                        Update: {
                           "accent_color"?: string | null,"greeting_latin"?: never,"greeting_meaning"?: never,"greeting_native"?: never,"greeting_script"?: never,"hero_image_path"?: string | null,"id"?: string | null,"is_live"?: boolean | null,"name"?: string | null,"slug"?: string | null,"sort_order"?: number | null,"story"?: never,"tagline"?: never
                         }
                        Relationships: [
                    
                  ]
                },"store_review_photos": {
                  Row: {
                    "id": string | null,"review_id": string | null,"sort_order": number | null,"storage_path": string | null
                  }
                  Relationships: [
                    {
      foreignKeyName: "review_photos_review_id_fkey"
      columns: ["review_id"]
isOneToOne: false
      referencedRelation: "reviews"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "review_photos_review_id_fkey"
      columns: ["review_id"]
isOneToOne: false
      referencedRelation: "store_reviews"
      referencedColumns: ["id"]
    }
                  ]
                },"store_reviews": {
                  Row: {
                    "body": string | null,"created_at": string | null,"display_name": string | null,"id": string | null,"is_verified_buyer": boolean | null,"product_id": string | null,"rating": number | null
                  }
                  Insert: {
                           "body"?: string | null,"created_at"?: string | null,"display_name"?: string | null,"id"?: string | null,"is_verified_buyer"?: boolean | null,"product_id"?: string | null,"rating"?: number | null
                         }
                        Update: {
                           "body"?: string | null,"created_at"?: string | null,"display_name"?: string | null,"id"?: string | null,"is_verified_buyer"?: boolean | null,"product_id"?: string | null,"rating"?: number | null
                         }
                        Relationships: [
                    {
      foreignKeyName: "reviews_product_id_fkey"
      columns: ["product_id"]
isOneToOne: false
      referencedRelation: "products"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "reviews_product_id_fkey"
      columns: ["product_id"]
isOneToOne: false
      referencedRelation: "store_products"
      referencedColumns: ["id"]
    }
                  ]
                },"store_variants": {
                  Row: {
                    "available": number | null,"id": string | null,"label": string | null,"options": Json | null,"price_cents": number | null,"product_id": string | null,"sort_order": number | null
                  }
                  Relationships: [
                    {
      foreignKeyName: "product_variants_product_id_fkey"
      columns: ["product_id"]
isOneToOne: false
      referencedRelation: "products"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "product_variants_product_id_fkey"
      columns: ["product_id"]
isOneToOne: false
      referencedRelation: "store_products"
      referencedColumns: ["id"]
    }
                  ]
                }
          }
          Functions: {
            "_cutoff_cycle":
{ Args: { "p_cycle": string }; Returns: number
                           },
"_is_verified_buyer":
{ Args: { "p_product": string,"p_user": string }; Returns: boolean
                           },
"_leaving_soon_max":
{ Args: Record<PropertyKey, never>; Returns: number
                           },
"_next_cycle_dates":
{ Args: { "p_cycle": Database["public"]['Tables']["cycles"]['Row'] }; Returns: {
              "cutoff_at": string,"est_arrival_on": string,"est_export_on": string
            }[]
                           },
"_open_next_cycle":
{ Args: { "p_cycle": string }; Returns: string
                           },
"_order_offer":
{ Args: { "p_order": string }; Returns: Json
                           },
"_set_stock_context":
{ Args: { "p_note": string,"p_reason": Database["public"]['Enums']["stock_reason"],"p_ref_id": string,"p_ref_type": string }; Returns: undefined
                           },
"_set_window":
{ Args: { "p_from": string,"p_kind": string,"p_note": string,"p_order": string,"p_to": string }; Returns: undefined
                           },
"_store_cycle":
{ Args: Record<PropertyKey, never>; Returns: {
              "cutoff_at": string,"est_arrival_on": string
            }[]
                           },
"_store_product_card":
{ Args: { "p_product_id": string }; Returns: Json
                           },
"_window_from":
{ Args: { "p_cycle": Database["public"]['Tables']["cycles"]['Row'],"p_order": Database["public"]['Tables']["orders"]['Row'] }; Returns: {
              "est_from": string,"est_to": string
            }[]
                           },
"accept_fast_offer":
{ Args: { "p_move": string,"p_payment_intent": string }; Returns: undefined
                           },
"admin_create_listing":
{ Args: { "p_listing": Json }; Returns: string
                           },
"admin_set_listed_qty":
{ Args: { "p_note"?: string,"p_qty_listed": number,"p_variant": string }; Returns: undefined
                           },
"admin_stale_variants":
{ Args: Record<PropertyKey, never>; Returns: {
              "label": string,"product_id": string,"product_name": string,"qty_confirmed_at": string,"qty_listed": number,"shop_name": string,"variant_id": string
            }[]
                           },
"advance_cycle":
{ Args: { "p_cycle": string }; Returns: Database["public"]['Enums']["cycle_status"]
                           },
"cancel_order":
{ Args: { "p_amount_cents": number,"p_order": string,"p_reason": string,"p_refund_ref": string }; Returns: undefined
                           },
"cancel_refund_cents":
{ Args: { "p_order": string,"p_reason": string }; Returns: number
                           },
"change_delivery_window":
{ Args: { "p_from": string,"p_note"?: string,"p_order": string,"p_to": string }; Returns: undefined
                           },
"checkout_context":
{ Args: { "p_promo_code"?: string,"p_variant_ids": (string)[] }; Returns: Json
                           },
"confirm_move_shipped":
{ Args: { "p_move": string }; Returns: Database["public"]['Enums']["move_offer_status"]
                           },
"create_order":
{ Args: { "p_order": Json }; Returns: {
              "order_id": string,"order_number": string
            }[]
                           },
"cutoff_cycle":
{ Args: { "p_cycle": string }; Returns: number
                           },
"dev_preview":
{ Args: Record<PropertyKey, never>; Returns: boolean
                           },
"generate_order_number":
{ Args: Record<PropertyKey, never>; Returns: string
                           },
"guest_order_lookup":
{ Args: { "p_email": string,"p_order_number": string }; Returns: Json
                           },
"increment_promo_uses":
{ Args: { "p_promo": string }; Returns: boolean
                           },
"is_admin":
{ Args: Record<PropertyKey, never>; Returns: boolean
                           },
"is_product_visible":
{ Args: { "p_product": string }; Returns: boolean
                           },
"item_refund_cents":
{ Args: { "p_item": string }; Returns: number
                           },
"mark_pickup":
{ Args: { "p_note"?: string,"p_photo_path"?: string,"p_pickup": string,"p_status": Database["public"]['Enums']["pickup_status"] }; Returns: undefined
                           },
"move_order":
{ Args: { "p_note"?: string,"p_order": string,"p_to_cycle": string }; Returns: string
                           },
"record_payout":
{ Args: { "p_method": string,"p_note"?: string,"p_pickups": (string)[],"p_receipt_path"?: string,"p_reference"?: string,"p_vendor": string }; Returns: string
                           },
"refund_order_item":
{ Args: { "p_amount_cents": number,"p_item": string,"p_refund_ref": string }; Returns: undefined
                           },
"review_eligibility":
{ Args: { "p_product": string }; Returns: Json
                           },
"roll_cycles":
{ Args: Record<PropertyKey, never>; Returns: number
                           },
"store_home":
{ Args: Record<PropertyKey, never>; Returns: Json
                           },
"store_my_order":
{ Args: { "p_order_number": string }; Returns: Json
                           },
"store_next_delivery":
{ Args: Record<PropertyKey, never>; Returns: {
              "est_delivery_from": string,"est_delivery_to": string,"order_by": string
            }[]
                           },
"store_product_page":
{ Args: { "p_product_slug": string,"p_region_slug": string }; Returns: Json
                           },
"store_region_page":
{ Args: { "p_region_slug": string }; Returns: Json
                           }
          }
          Enums: {
            "app_role": "customer"|"admin","content_status": "draft"|"approved","cycle_status": "open"|"collecting"|"packed"|"exported"|"arrived"|"fulfilling"|"closed","discount_type": "percentage"|"fixed","fulfilment_mode": "order_first","move_offer_status": "none"|"offered"|"accepted"|"lapsed","ops_desk": "us"|"india","order_item_status": "active"|"unavailable"|"refunded","order_status": "pending_payment"|"confirmed"|"collecting"|"packed"|"in_transit"|"arrived"|"shipped"|"delivered"|"cancelled"|"refunded","payment_status": "pending"|"paid"|"failed"|"refunded"|"partially_refunded","pickup_status": "pending"|"picked"|"unavailable","product_status": "draft"|"live"|"paused"|"archived","product_type": "clothing"|"spice","review_status": "pending"|"approved"|"rejected","shipping_method": "standard"|"express","stock_reason": "listed"|"adjusted"|"reserved"|"released"|"picked"|"unavailable","vendor_status": "prospect"|"active"|"paused"
          }
          CompositeTypes: {
            [_ in never]: never
          }
        }
}

type DatabaseWithoutInternals = Omit<Database, '__InternalSupabase'>

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never
> = DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
  ? (DefaultSchema["Tables"] & DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
      Row: infer R
    }
    ? R
    : never
  : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never
> = DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
  ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
      Insert: infer I
    }
    ? I
    : never
  : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never
> = DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
  ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
      Update: infer U
    }
    ? U
    : never
  : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never
> = DefaultSchemaEnumNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
  ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
  : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never
> = PublicCompositeTypeNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
  ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
  : never

export const Constants = {
  "public": {
          Enums: {
            "app_role": ["customer", "admin"],"content_status": ["draft", "approved"],"cycle_status": ["open", "collecting", "packed", "exported", "arrived", "fulfilling", "closed"],"discount_type": ["percentage", "fixed"],"fulfilment_mode": ["order_first"],"move_offer_status": ["none", "offered", "accepted", "lapsed"],"ops_desk": ["us", "india"],"order_item_status": ["active", "unavailable", "refunded"],"order_status": ["pending_payment", "confirmed", "collecting", "packed", "in_transit", "arrived", "shipped", "delivered", "cancelled", "refunded"],"payment_status": ["pending", "paid", "failed", "refunded", "partially_refunded"],"pickup_status": ["pending", "picked", "unavailable"],"product_status": ["draft", "live", "paused", "archived"],"product_type": ["clothing", "spice"],"review_status": ["pending", "approved", "rejected"],"shipping_method": ["standard", "express"],"stock_reason": ["listed", "adjusted", "reserved", "released", "picked", "unavailable"],"vendor_status": ["prospect", "active", "paused"]
          }
        }
} as const
