/**
 * design/pages/_shared/build-tokens.mjs: writes tokens.css (CSS variables) from packages/tokens/tokens.js, so the
 * page mockups use the real token values and never a copy that drifts. Run after the tokens change:
 *   node design/pages/_shared/build-tokens.mjs
 */
import { createRequire } from 'node:module';
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const here = path.dirname(fileURLToPath(import.meta.url));
const tokens = createRequire(import.meta.url)('../../../packages/tokens/tokens.js');

const quote = (f) => (/[\s\d]/.test(f) && !f.includes('-serif') ? `'${f}'` : f);
const lines = [
  ...Object.entries(tokens.colors).map(([k, v]) => `  --${k}: ${v};`),
  ...Object.entries(tokens.radius).map(([k, v]) => `  --radius-${k}: ${v};`),
  ...Object.entries(tokens.duration).map(([k, v]) => `  --duration-${k}: ${v};`),
  ...Object.entries(tokens.fonts).map(([k, v]) => `  --font-${k}: ${v.map(quote).join(', ')};`),
];

writeFileSync(
  path.join(here, 'tokens.css'),
  `/* Generated by build-tokens.mjs from packages/tokens/tokens.js. Do not edit by hand. */\n:root {\n${lines.join('\n')}\n}\n`,
);
console.log(`tokens.css: ${lines.length} variables`);
