/**
 * design/pages/_shared/build-tokens.mjs: writes tokens.css (CSS variables) from packages/tokens/tokens.js and
 * brand.js (the logo's India mark, D-077) from packages/shared/src/india-map/mark.ts, so the page mockups use the real
 * values and never a copy that drifts. Run after either changes:
 *   node design/pages/_shared/build-tokens.mjs
 */
import { createRequire } from 'node:module';
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const here = path.dirname(fileURLToPath(import.meta.url));
const tokens = createRequire(import.meta.url)('../../../packages/tokens/tokens.js');

const quote = (f) => (/[\s\d]/.test(f) && !f.includes('-serif') ? `'${f}'` : f);
const lines = [
  ...Object.entries(tokens.colors).map(([k, v]) => `  --${k}: ${v};`),
  ...Object.entries(tokens.radius).map(([k, v]) => `  --radius-${k}: ${v};`),
  ...Object.entries(tokens.duration).map(([k, v]) => `  --duration-${k}: ${v};`),
  ...Object.entries(tokens.fonts).map(([k, v]) => `  --font-${k}: ${v.map(quote).join(', ')};`),
];

writeFileSync(
  path.join(here, 'tokens.css'),
  `/* Generated by build-tokens.mjs from packages/tokens/tokens.js. Do not edit by hand. */\n:root {\n${lines.join('\n')}\n}\n`,
);
console.log(`tokens.css: ${lines.length} variables`);

const mark = readFileSync(path.join(here, '../../../packages/shared/src/india-map/mark.ts'), 'utf8');
const viewBox = mark.match(/viewBox: '([^']+)'/)[1];
const d = mark.match(/path:\s*'([^']+)'/)[1];
writeFileSync(
  path.join(here, 'brand.js'),
  `/* Generated by build-tokens.mjs from packages/shared/src/india-map/mark.ts. Do not edit by hand. */\n` +
    `window.INDIA_MARK = ${JSON.stringify({ viewBox, path: d })};\n`,
);
console.log(`brand.js: mark ${viewBox}, ${d.length} chars`);
