import data from './india-map.json';

/**
 * The India map (design.md §Visual system 4): one SVG path per region, keyed by the region slug, from DataMeet's
 * state boundaries (CC BY 4.0, D-052; the credit must stay visible wherever the map is shown). Generated by
 * scripts/build-india-map.mjs. `centers` are marker points for regions too small to tap or point at.
 */
export interface IndiaMap {
  viewBox: string;
  paths: Record<string, string>;
  centers: Record<string, number[]>;
}

export const INDIA_MAP: IndiaMap = data;

/** Regions small enough to need a marker dot as well as their shape. */
export const TINY_REGIONS = ['chandigarh', 'delhi', 'goa', 'puducherry', 'lakshadweep', 'dadra-and-nagar-haveli-and-daman-and-diu'];
